### ISSUE TITLE
Internal Error '/auth/google/callback  undefined'

### ISSUE THREAD

**Issue by singhnsk** [julianlam/nodebb-plugin-sso-google#22]
I'm running the latest public version 1.1.0 with Google SSO setup. When tried to login using Google, it takes me to the Google permissions page and then when I'm sent back here, it throws the following error.

```
 Internal error.

Oops! Looks like something went wrong!

/auth/google/callback

undefined
```

A loot at admin/advanced/logs shows the following:
```
 [21556] - [31merror[39m: /auth/google/callback
 TokenError
    at Strategy.OAuth2Strategy.parseErrorResponse (/home/ubuntu/NodeBB/node_modules/nodebb-plugin-sso-google/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/lib/strategy.js:320:12)
    at Strategy.OAuth2Strategy._createOAuthError (/home/ubuntu/NodeBB/node_modules/nodebb-plugin-sso-google/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/lib/strategy.js:367:16)
    at /home/ubuntu/NodeBB/node_modules/nodebb-plugin-sso-google/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/lib/strategy.js:166:45
    at /home/ubuntu/NodeBB/node_modules/nodebb-plugin-sso-google/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:177:18
    at passBackControl (/home/ubuntu/NodeBB/node_modules/nodebb-plugin-sso-google/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:123:9)
    at IncomingMessage.<anonymous> (/home/ubuntu/NodeBB/node_modules/nodebb-plugin-sso-google/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)

```

**Comment by julianlam** [comment]
Have you enabled the "Google+ API" in your app console?

**Comment by singhnsk** [comment]
Yes I have. With the Google + API disabpled, I get the following error instead. So it really is enabled and functional as I'm taken to the permissions page, approved and then sent back to the forum. It is there where it fails.

```
Error: invalid_client

The OAuth client was not found.
```

**Comment by julianlam** [comment]
Hm... in that case are you using any sort of reverse proxy with SSL? Could be a configuration problem causing token to not be retrieve and processed correctly.

**Comment by singhnsk** [comment]
None. I'm using NGINX, but I'm not on SSL. What else could be the reason?

**Comment by singhnsk** [comment]
Not sure what did the trick, but creating a new project and adding that client ID and secret made the request go fine.
I also gave NodeBB a proper shut down and restart before testing the new project, so maybe that helped too. Whatever it was, all cool! Thanks for being quick to help :D
